### PR TITLE
Update grammatically errors on README.md

### PR DESCRIPTION
**Pull request by Aholicknight**

### CODE REVIEW

**Review by jaykali — APPROVED** [review]

**Comment by Aholicknight** [comment]
Are you going to merge this?

**Comment by jaykali** [comment]
I don't think this is active.

**Comment by Aholicknight** [comment]
What do you mean by "this is active" this corrects the grammar issues in the readme with proper English instead of broken english.

**Comment by jaykali** [comment]
I mean to say the owner of this repository is not active for a year.

**Comment by Aholicknight** [comment]
I see. I will close this.

**Pull request closed without merging**
